jotform/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('installation/',include('installation.urls')),
    path('', include('manager.urls')),
    # re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]


urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

handler400 ='errors.views.error_400'
handler403 ='errors.views.error_403'
handler404 ='errors.views.error_404'
handler500='errors.views.error_500'

manager/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.db.models.signals import post_save,pre_save
from django.dispatch import receiver
from manager.addons import send_email
import random
from django.utils.crypto import get_random_string
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models import Max
from django.utils.translation import gettext_lazy as _
import environ
env=environ.Env()
environ.Env.read_env()

class ExtendedAdmin(models.Model):
    user=models.OneToOneField(User,primary_key=True,on_delete=models.CASCADE)
    location=models.CharField(null=True,blank=True,max_length=100)
    main=models.BooleanField(default=False)
    is_installed=models.BooleanField(default=False)

    class Meta:
        db_table='extended_admin'
        verbose_name_plural='extended_admins'

    def __str__(self):
        return f'{self.user.username} site extended admin'


        
#generate random
def generate_id():
    return get_random_string(6,'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKMNOPQRSTUVWXYZ0123456789')




@receiver(post_save, sender=ExtendedAdmin)
def send_installation_email(sender, instance, created, **kwargs):
    if created:
        if instance.is_installed:
            #site is installed
            subject='Congragulations:Site installed successfully.'
            email=instance.user.email
            message={
                        'user':instance.user,
                        'site_name':instance.user.siteconstants.site_name,
                        'site_url':instance.user.siteconstants.site_url
                    }
            template='emails/installation.html'
            send_email(subject,email,message,template)





def bgcolor():
    hex_digits=['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']
    digit_array=[]
    for i in range(6):
        digits=hex_digits[random.randint(0,15)]
        digit_array.append(digits)
    joined_digits=''.join(digit_array)
    color='#'+joined_digits
    return color





user_roles=[
            ('Tertiary','View only'),
            ('Secondary','View | Edit'),
            ('Admin','View | Edit  | Admin'),
        ]





class ExtendedAuthUser(models.Model):
    user=models.OneToOneField(User,primary_key=True,on_delete=models.CASCADE)
    phone=PhoneNumberField(null=True,blank=True,verbose_name='phone',unique=True,max_length=13)
    initials=models.CharField(max_length=10,blank=True,null=True)
    bgcolor=models.CharField(max_length=10,blank=True,null=True,default=bgcolor)
    company=models.CharField(max_length=100,null=True,blank=True,default=env('SITE_NAME'))
    profile_pic=models.ImageField(upload_to='profiles/',null=True,blank=True,default="placeholder.jpg")
    role=models.CharField(choices=user_roles,max_length=200,null=True,blank=True)
    created_on=models.DateTimeField(default=now)
    class Meta:
        db_table='extended_auth_user'
        verbose_name_plural='extended_auth_users'
        permissions=(
            ("can_view","Can view"),
            ("can_edit","Can edit"),
            ("can_see_invoice","Can see invoice"),
        )
    def __str__(self)->str:
        return f'{self.user.username} extended auth profile'




#generate random
def generate_serial():
    return get_random_string(12,'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKMNOPQRSTUVWXYZ0123456789')
 

 




class ContactModel(models.Model):
    name=models.CharField(max_length=100,blank=True,null=True)
    phone=PhoneNumberField(null=True,blank=True,verbose_name='phone',max_length=13)
    subject=models.CharField(max_length=100,null=True,blank=True)
    email=models.CharField(max_length=100,blank=True,null=True)
    is_read=models.BooleanField(default=False,blank=True,null=True)
    message=models.TextField(blank=True,null=True)
    reply=models.TextField(blank=True,null=True)
    created_on=models.DateTimeField(default=now)
    class Meta:
        db_table='contact_tbl'
        verbose_name_plural='contact_tbl'
    def __str__(self)->str:
        return f'{self.name} contact message'

class ApplicationModel(models.Model):
    application_serial=models.CharField(max_length=255,default=generate_serial)
    applicant_fname=models.CharField(max_length=100,blank=True,null=True)
    applicant_mname=models.CharField(max_length=100,blank=True,null=True)
    applicant_lname=models.CharField(max_length=100,blank=True,null=True)
    prefix=models.CharField(max_length=100,null=True,blank=True)
    email=models.CharField(max_length=100,null=True,blank=True)
    mobile_phone=PhoneNumberField(null=True,blank=True,verbose_name='phone',max_length=13) 
    phone=PhoneNumberField(null=True,blank=True,verbose_name='phone',max_length=13)
    fax=models.CharField(max_length=100,null=True,blank=True)
    address1=models.CharField(max_length=100,null=True,blank=True)
    address2=models.CharField(max_length=100,null=True,blank=True)
    city=models.CharField(max_length=100,null=True,blank=True)
    state=models.CharField(max_length=100,null=True,blank=True)
    zip_code=models.CharField(max_length=100,null=True,blank=True)
    dob=models.DateField(null=True,blank=True)
    apply_as=models.CharField(max_length=100,null=True,blank=True)
    biz_location1=models.CharField(max_length=100,null=True,blank=True)
    biz_location2=models.CharField(max_length=100,null=True,blank=True)
    biz_city=models.CharField(max_length=100,null=True,blank=True)
    biz_state=models.CharField(max_length=100,null=True,blank=True)
    biz_zip_code=models.CharField(max_length=100,null=True,blank=True)
    marketing_material=models.FileField(upload_to='uploads/',null=True,blank=True,default='')
    marketing_information=models.FileField(upload_to='uploads/',null=True,blank=True,default='')
    statement=models.CharField(max_length=100,null=True,blank=True)
    statement_information=models.FileField(upload_to='uploads/',null=True,blank=True,default='')
    been_financed=models.CharField(max_length=100,null=True,blank=True)
    lender_name=models.CharField(max_length=100,null=True,blank=True)
    finance_was_for=models.CharField(max_length=100,null=True,blank=True)
    loan_reason=models.CharField(max_length=100,null=True,blank=True)
    project_gross_value=models.CharField(max_length=100,null=True,blank=True)
    loan_amount=models.IntegerField(null=True,blank=True)
    created_at=models.DateTimeField(default=now)
    class Meta:
        db_table='application_table'
        verbose_name_plural='application_table'
        ordering=('created_at',)

    def delete(self, using=None,keep_parents=False):
        if self.marketing_material or self.statement_information or self.marketing_information:
            self.marketing_material.storage.delete(self.marketing_material.name)
            self.marketing_information.storage.delete(self.marketing_information.name)
            self.statement_information.storage.delete(self.statement_information.name)
        super().delete()

manager/forms.py
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from .models import *
from django import forms
from django.contrib.auth.forms import PasswordResetForm, UserCreationForm,UserChangeForm,PasswordChangeForm
from django.contrib.auth.forms import User
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from django.contrib.auth.hashers import check_password
from django.core.validators import FileExtensionValidator,URLValidator
from installation.models import SiteConstants
from django.contrib.auth import authenticate

class UserResetPassword(PasswordResetForm):
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Enter email address'}),error_messages={'required':'Email address is required'})

    def clean_email(self):
        email=self.cleaned_data['email']
        if  not User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email address does not exist')
        try:
            validate_email(email)
        except ValidationError:
            raise forms.ValidationError('Invalid email address')
        return email


class UsersContactForm(forms.ModelForm):
    name=forms.CharField(widget=forms.TextInput(attrs={'aria-required':'true','class':'form-control','placeholder':'Full name','aria-label':'name'}),error_messages={'required':'Full name is required'})
    phone=PhoneNumberField(widget=PhoneNumberPrefixWidget(attrs={'aria-required':'true','class':'form-control','type':'tel','aria-label':'phone','placeholder':'Phone'},initial="IN"),error_messages={'required':'Phone number is required'})
    email=forms.EmailField(widget=forms.EmailInput(attrs={'aria-required':'true','class':'form-control','placeholder':'Email address','aria-label':'email'}),error_messages={'required':'Email address is required'})
    subject=forms.CharField(widget=forms.TextInput(attrs={'aria-required':'true','class':'form-control','placeholder':'subject ','aria-label':'subject'}),error_messages={'required':'Subject is required'})
    message=forms.CharField(widget=forms.Textarea(attrs={'rows':5,'aria-required':'true','class':'form-control','placeholder':'Message','aria-label':'message'}),error_messages={'required':'Message is required','min_length':'enter atleast 6 characters long'})

    class Meta:
        model=ContactModel
        fields=['name','phone','email','subject','message',]


    def clean_name(self):
        name=self.cleaned_data['name']
        if len(name.split(" ")) > 1:
            first_name=name.split(" ")[0]
            last_name=name.split(" ")[1]
            if not str(first_name).isalpha():
                raise forms.ValidationError('only characters are allowed')
            elif not str(last_name).isalpha():
                raise forms.ValidationError('only characters are allowed')
        return name

           

    def clean_email(self):
        email=self.cleaned_data['email']
        try:
            validate_email(email)
        except ValidationError as e:
            raise forms.ValidationError('invalid email address')
        return email

opt1=[
            ("Sole proprietor","Sole proprietor"),
            ("Partnership","Partnership"),
            ("Corporation","Corporation"),
        ]
opt2=[
            ("Yes","Yes"),
            ("No","No"),
        ]
class ApplicationForm(forms.ModelForm):
    applicant_fname=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'applicant_fname','class':'form-control','placeholder':'Applicant first name'}),error_messages={'required':'First name is required'})
    applicant_mname=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'applicant_mname','class':'form-control','placeholder':'Applicant middle name'}),error_messages={'required':'Middle is required'})
    applicant_lname=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'applicant_lname','class':'form-control','placeholder':'Applicant last name'}),error_messages={'required':'Last name is required'})
    prefix=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'prefix','class':'form-control','placeholder':'Prefix'}),error_messages={'required':'Prefix is required'})
    email=forms.EmailField(widget=forms.EmailInput(attrs={'aria-label':'email','class':'form-control','placeholder':'myname@example.com'}),error_messages={'required':'Email is required'})
    mobile_phone=PhoneNumberField(widget=PhoneNumberPrefixWidget(attrs={'aria-required':'true','class':'form-control','type':'tel','aria-label':'phone','placeholder':'Mobile phone number'},initial="Ke"),error_messages={'required':'Mobile phone number is required'})
    phone=PhoneNumberField(widget=PhoneNumberPrefixWidget(attrs={'aria-required':'true','class':'form-control','type':'tel','aria-label':'phone','placeholder':'Phone number'},initial="Ke"),error_messages={'required':'Phone number is required'})
    fax=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'fax','class':'form-control','placeholder':'Fax'}),required=False)
    address1=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'address1','class':'form-control','placeholder':'Street address'}),error_messages={'required':'Street address is required'})
    address2=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'address2','class':'form-control','placeholder':'Street address line 2'}),required=False)
    city=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'city','class':'form-control','placeholder':'City'}),required=False)
    state=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'state','class':'form-control','placeholder':'State'}),required=False)
    zip_code=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'zip_code','class':'form-control','placeholder':'zip code'}),required=False)
    dob=forms.DateField(widget=forms.DateInput(attrs={'pattern':'[0-9]{2}-[0-9]{2}-[0-9]{4}','type':'Date','class':'form-control','placeholder':'date of birth'}),error_messages={'required':'DOB is required'})
    biz_location1=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'biz_location1','class':'form-control','placeholder':'Businness Street address'}),error_messages={'required':'Businness Street address is required'})
    biz_location2=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'biz_location2','class':'form-control','placeholder':'Businness Street address line 2'}),required=False)
    biz_city=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'biz_city','class':'form-control','placeholder':'Businness City'}),required=False)
    biz_state=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'biz_state','class':'form-control','placeholder':'Businness State'}),required=False)
    biz_zip_code=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'biz_zip_code','class':'form-control','placeholder':'zip code'}),required=False)
    apply_as=forms.ChoiceField(choices=opt1,widget=forms.RadioSelect(attrs={'aria-label':'apply_as','class':'form-check-input','type':'radio'}),error_messages={'required':'Applying as category is required'})
    marketing_material=forms.FileField(widget=forms.FileInput(attrs={'aria-label':'marketing_material','class':'custom-file-input','id':'customFileInput1'}),required=False)
    marketing_information=forms.FileField(widget=forms.FileInput(attrs={'aria-label':'marketing_information','class':'custom-file-input','id':'customFileInput2'}),required=False)
    statement=forms.ChoiceField(choices=opt2,widget=forms.RadioSelect(attrs={'aria-label':'statement','class':'form-check-input','type':'radio'}),error_messages={'required':'This field is required'})
    statement_information=forms.FileField(widget=forms.FileInput(attrs={'aria-label':'statement_information','class':'custom-file-input','id':'customFileInput3'}),required=False)
    been_financed=forms.ChoiceField(choices=opt2,widget=forms.RadioSelect(attrs={'aria-label':'been_financed','class':'form-check-input','type':'radio'}),error_messages={'required':'This field  is required'})
    lender_name=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'lender_name','class':'form-control','placeholder':'Lender name'}),required=False)
    finance_was_for=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'finance_was_for','class':'form-control','placeholder':'Finnace was for'}),required=False)
    loan_reason=forms.CharField(widget=forms.Textarea(attrs={'cols':20,'rows':5,'aria-label':'loan_reason','class':'form-control','placeholder':'Loan reason'}),required=False)
    project_gross_value=forms.CharField(widget=forms.TextInput(attrs={'aria-label':'project_gross_value','class':'form-control','placeholder':'Project gross value'}),required=False)
    loan_amount=forms.CharField(widget=forms.NumberInput(attrs={'aria-label':'loan_amount','class':'form-control','placeholder':'Loan amount'}),error_messages={'required':'Loan amount  is required'})
    agree=forms.BooleanField(widget=forms.CheckboxInput(attrs={'aria-label':'agree','class':'form-check-input','type':'checkbox','id':'exampleRadio1'}),error_messages={'required':'This field is required'})
    class Meta:
        model=ApplicationModel
        fields=[
                'applicant_fname',
                'applicant_mname',
                'applicant_lname',
                'mobile_phone','phone','fax',
                'prefix',
                'email',
                'address1','address2',
                'city',
                'state',
                'zip_code',
                'dob',
                'biz_location1',
                'biz_location2',
                'biz_city',
                'biz_state',
                'biz_zip_code','apply_as','marketing_material','marketing_information','statement','been_financed','statement_information','lender_name','finance_was_for','loan_reason','project_gross_value','loan_amount',
            ]

templates/panel/edit_admin.html
{% extends 'panel/base.html' %}
{% load static %}
{% block body %}
 <div class="container-fluid">
    <div class="row">
        <div class="col-md-12 m-b-30">
            <!-- begin page title -->
            <div class="d-block d-sm-flex flex-nowrap align-items-center">
                <div class="page-title mb-2 mb-sm-0">
                    <h1>Edit Admin</h1>
                </div>
                <div class="ml-auto d-flex align-items-center">
                    <nav>
                        <ol class="breadcrumb p-0 m-b-0">
                            <li class="breadcrumb-item">
                                <a  href="{% url 'admin dashboard' %}"><i class="ti ti-home"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{% url 'admin dashboard' %}">Home</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{% url 'site admins' %}">View admins</a>
                            </li>
                            <li class="breadcrumb-item active text-primary" aria-current="page">Edit {{admin.get_full_name}}</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- end page title -->
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6 mx-auto">
            <div class="card card-statistics">
                <div class="card-header">
                    <div class="card-heading">
                        <h4 class="card-title text-capitalize">{{admin.get_full_name }} Details</h4>
                    </div>
                </div>
                <div class="card-body"> 
                    <form class="RegForm" method="post" action="{% url 'edit admin' id=admin.id %}" novalidate>
                        {% csrf_token %}
                        <div class="form-group">               
                            <label for="id_theme_color">Profile pic</label>
                            <div class="custom-file" style="cursor:pointer">
                                {{form1.profile_pic}}
                                <label for="customFileInput" class="custom-file-label">Browse files</label>
                            </div>
                            current: <a class="text-pimary" href="/media/logos{{admin.extendedauthuser.profile_pic.url}}">{{admin.extendedauthuser.profile_pic}}</a>
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">
                            <label for="id_first_name">First Name</label>
                            {{form1.first_name}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">
                            <label for="id_last_name">Last Name</label>
                            {{form1.last_name}}
                            <div class="feedback"></div>
                        </div>
                       
                        <div class="form-group">               
                            <label for="id_email">Email</label>
                            {{form1.email}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_username">Username</label>
                            {{form1.username}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_username">Role</label>
                            {{form2.role}}
                            <div class="feedback"></div>
                        </div>
                        <label for="id_phone">Phone</label>
                        <div class="form-group">               
                            {{form2.phone}}
                            <div class="feedback"></div>
                        </div>
                        <div class="text-center" style="margin-top:60px">
                            <button type="submit" class="btn btn-primary">
                                <span></span><span>submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>  
    </div>
 </div>
{% endblock %}

templates/panel/edit_employee.html
{% extends 'panel/base.html' %}
{% load static %}
{% block body %}
 <div class="container-fluid">
    <div class="row">
        <div class="col-md-12 m-b-30">
            <!-- begin page title -->
            <div class="d-block d-sm-flex flex-nowrap align-items-center">
                <div class="page-title mb-2 mb-sm-0">
                    <h1>Edit Employee</h1>
                </div>
                <div class="ml-auto d-flex align-items-center">
                    <nav>
                        <ol class="breadcrumb p-0 m-b-0">
                            <li class="breadcrumb-item">
                                <a  href="{% url 'admin dashboard' %}"><i class="ti ti-home"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{% url 'admin dashboard' %}">Home</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{% url 'site employees' %}">View employees</a>
                            </li>
                            <li class="breadcrumb-item active text-primary" aria-current="page">Edit {{employee.get_full_name}}</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- end page title -->
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6 mx-auto">
            <div class="card card-statistics">
                <div class="card-header">
                    <div class="card-heading">
                        <h4 class="card-title text-capitalize">{{employee.get_full_name }} Details</h4>
                    </div>
                </div>
                <div class="card-body"> 
                    <form class="RegForm" method="post" action="{% url 'edit employee' id=employee.id %}" novalidate>
                        {% csrf_token %}
                        <div class="form-group">               
                            <label for="id_theme_color">Profile pic</label>
                            <div class="custom-file" style="cursor:pointer">
                                {{form1.profile_pic}}
                                <label for="customFileInput" class="custom-file-label">Browse files</label>
                            </div>
                            current: <a class="text-pimary" href="/media/logos{{employee.extendedauthuser.profile_pic.url}}">{{employee.extendedauthuser.profile_pic}}</a>
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">
                            <label for="id_first_name">First Name</label>
                            {{form1.first_name}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">
                            <label for="id_last_name">Last Name</label>
                            {{form1.last_name}}
                            <div class="feedback"></div>
                        </div>
                       
                        <div class="form-group">               
                            <label for="id_email">Email</label>
                            {{form1.email}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_username">Username</label>
                            {{form1.username}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_username">Role</label>
                            {{form2.role}}
                            <div class="feedback"></div>
                        </div>
                        <label for="id_phone">Phone</label>
                        <div class="form-group">               
                            {{form2.phone}}
                            <div class="feedback"></div>
                        </div>
                        <div class="text-center" style="margin-top:60px">
                            <button type="submit" class="btn btn-primary">
                                <span></span><span>submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>  
    </div>
 </div>
{% endblock %}

templates/panel/edit_query.html
{% extends 'panel/base.html' %}
{% load static %}
{% block body %}
 <div class="container-fluid">
    <div class="row">
        <div class="col-md-12 m-b-30">
            <!-- begin page title -->
            <div class="d-block d-sm-flex flex-nowrap align-items-center">
                <div class="page-title mb-2 mb-sm-0">
                    <h1>Answer Query</h1>
                </div>
                <div class="ml-auto d-flex align-items-center">
                    <nav>
                        <ol class="breadcrumb p-0 m-b-0">
                            <li class="breadcrumb-item">
                                <a  href="{% url 'admin dashboard' %}"><i class="ti ti-home"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{% url 'admin dashboard' %}">Home</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{% url 'customers queries' %}">View queries</a>
                            </li>
                            <li class="breadcrumb-item active text-primary" aria-current="page">Answer {{query.name}}'s query</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- end page title -->
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6 mx-auto">
            <div class="card card-statistics">
                <div class="card-header">
                    <div class="card-heading text-center">
                        <h4 class="card-title text-capitalize">{{query.name }}'s Query</h4>
                    </div>
                </div>
                <div class="card-body"> 
                    <form class="RegForm" method="post" action="" novalidate>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_name">Name</label>
                            {{form.name}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">
                            <label for="id_name">Category</label>
                            {{form.user}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_email">Email</label>
                            {{form.email}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_username">Query</label>
                            {{form.query}}
                            <div class="feedback"></div>
                        </div>
                        <label for="id_answer">Answer</label>
                        <div class="form-group">               
                            {{form.answer}}
                            <div class="feedback"></div>
                        </div>
                        <div class="text-center" style="margin-top:60px">
                            <button type="submit" class="btn btn-primary">
                                <span></span><span>submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>  
    </div>
 </div>
{% endblock %}